---

- name: Make HomelabOS data directories.
  file:
    path: "{{ item }}"
    state: directory
    mode: "1777"
  loop:
    - /var/homelabos/traefik
    - /etc/docker
  ignore_errors: "yes"

- name: Configure docker log settings
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json

- name: Install necessities and nice-to-haves
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - cifs-utils
      - curl
      - software-properties-common
      - git
      - htop
      - iftop
      - iotop
      - mosh
      - nfs-common
      - screen
      - sudo
      - unattended-upgrades
      - vim
      - zsh
      - docker
      - docker-compose
  tags:
    - dependencies

- name: timezone - configure /etc/timezone
  copy:
    content: "{{ common_timezone | regex_replace('$', '\n') }}"
    dest: /etc/timezone
    owner: root
    group: root
    mode: 0644
  register: common_timezone_config

- name: timezone - Set localtime to UTC
  file: src=/usr/share/zoneinfo/Etc/UTC dest=/etc/localtime
  when: common_timezone_config.changed

- name: timezone - reconfigure tzdata
  command: dpkg-reconfigure --frontend noninteractive tzdata
  when: common_timezone_config.changed

- name: Ensure locale en_US.UTF-8 locale is present
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: Configure Traefik.
  template: src=traefik.toml dest=/var/homelabos/traefik/traefik.toml

- name: Configure SSL
  file:
    path: /var/homelabos/traefik/acme.json
    mode: 0600
    state: touch

- name: Get UID
  command: id -u
  register: uid_output
  become: false

- name: Get GID
  command: id -g
  register: gid_output
  become: false

- name: Create Media Folders / NAS Mount Points
  file:
    path: "{{ storage_dir }}/{{ item }}"
    state: directory
  with_items:
    - "Backups"
    - "Books"
    - "Documents"
    - "Downloads"
    - "Music"
    - "Movies"
    - "Pictures"
    - "TV"

- name: Configure NAS - Public NFS Shares
  when: 
    - nas_enable
    - nas_mount_type == "nfs"
  lineinfile:
    path: /etc/fstab
    line: "{{ nas_host }}:{{ nas_share_path }}/{{ item }} {{ storage_dir }}/{{ item }} nfs auto,nofail,noatime,nolock,intr,tcp,actimeo=1800 0 0"
  with_items:
    - "Backups"
    - "Books"
    - "Documents"
    - "Downloads"
    - "Music"
    - "Movies"
    - "Pictures"
    - "TV"

- name: Configure NAS - Samba Shares
  when:
    - nas_enable
    - nas_mount_type == "smb"
  lineinfile:
    path: /etc/fstab
    line: "//{{ nas_host }}/{{ item }}  {{ storage_dir }}/{{ item }}  cifs  nobrl,username={{ nas_user }},vers=2.0,dom={{ nas_workgroup }},password={{ nas_pass }},uid={{ uid_output.stdout }},gid={{ gid_output.stdout }},iocharset=utf8,file_mode=0777,dir_mode=0770  0  0"
  with_items:
    - "Backups"
    - "Books"
    - "Documents"
    - "Downloads"
    - "Music"
    - "Movies"
    - "Pictures"
    - "TV"

- name: Mount NAS Drives
  when: nas_enable
  command: mount -a
  args:
    warn: "no"
  ignore_errors: "yes"

- name: Configure HomelabOS systemd service.
  template: src=homelabos.service dest=/etc/systemd/system/homelabos.service

# Hacky ansible workaround. Would love to remove these 4 tasks.
# Long story short it ensures the `tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"` bit can work.
- name: Ensure tor host folder exists
  file:
    path: /var/lib/tor/ssh-onion/
    state: directory

- name: Ensure tor host folder exists
  file:
    path: /var/lib/tor/http-onion/
    state: directory

- name: Ensure blank tor host files exist
  file:
    path: /var/lib/tor/ssh-onion/hostname
    state: touch

- name: Ensure blank tor host files exist
  file:
    path: /var/lib/tor/http-onion/hostname
    state: touch
# / Hack

- name: Read Tor connection info
  shell: cat /var/lib/tor/http-onion/hostname
  register: tor_http_domain_file

- name: Copy HomelabOS docker-compose.yml file into place.
  template:
    src: docker-compose.traefik.yml.j2
    dest: /var/homelabos/traefik/docker-compose.traefik.yml
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"

- name: Create HomelabOS hosts file.
  file:
    path: /var/homelabos/homelab_hosts
    state: touch

- name: Configure HomelabOS hosts file. You can find it at /var/homelabos/homelab_hosts on your server.
  lineinfile:
    path: /var/homelabos/homelab_hosts
    line: "{{ ansible_host }} {{ service_item }}.{{ domain }} {{ service_item }}"
  when: "lookup('vars', 'enable_' ~ service_item)"
  loop: "{{ enabled_services|flatten(levels=1) }}"
  loop_control:
    loop_var: service_item

- name: Pull HomelabOS Traefik Image
  command: docker-compose -f /var/homelabos/traefik/docker-compose.traefik.yml pull

- name: Start HomelabOS
  systemd:
    name: homelabos
    enabled: "yes"
    daemon-reload: "yes"
    state: restarted
  ignore_errors: "yes"
