---
- name: Make factorio directory.
  file:
    path: "{{ volumes_root }}/factorio"
    state: directory

- name: Copy factorio docker-compose.yml file into place.
  template:
    src: docker-compose.factorio.yml.j2
    dest: "{{ volumes_root }}/factorio/docker-compose.yml"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"

- name: Configure factorio systemd service.
  template:
    src: service.j2
    dest: /etc/systemd/system/factorio.service

- name: Start factorio
  systemd:
    name: factorio
    enabled: "yes"
    daemon-reload: "yes"
    state: started
