---
image: python:alpine

before_script:
  - pip install mkdocs
  - pip install mkdocs-material
  - pip install yamllint

pages:
  script:
    - mkdocs build
    - mv site public
  artifacts:
    paths:
      - public
  only:
    - master

lint_yaml_files:
  script:
    - find . -type f -name '*.yml*' | sed 's|\./||g' | egrep -v '(\.kitchen/|\[warning\]|\.molecule/)' | xargs yamllint -f parsable
...
