---
# This is the top-level playbook that defines our entire infrastructure.

- hosts: all
  become: True
  gather_facts: True
  tags: common

  roles:
    - common

- hosts: all
  become: True
  gather_facts: True
  tags: homelabos

  roles:
    - homelabos
    - transmission
