---

# Configure the server itslef
- hosts: all
  become: True
  gather_facts: True
  tags: common

  roles:
    # Install Docker, configure basic server settings
    - common
    # Configure a TOR hidden service for remote access without a public IP
    # - { role: systemli.hidden-service }

# Install and configure HomelabOS services
- hosts: all
  become: True
  gather_facts: True
  tags: homelabos

  roles:
    - homelabos
