site_name: HomelabOS

repo_url: https://gitlab.com/NickBusey/HomelabOS
edit_uri: edit/master/docs

theme:
  name: material
  logo:
    icon: home

pages:
  - Home: index.md
  - Installation: setup/installation.md
  - Getting Started: setup/gettingstarted.md
  - Setup:
    - Backups: setup/backups.md
    - SMTP: setup/smtp.md
    - Tor Onion Services: setup/tor.md
    - VPN Setup: setup/vpn.md
  - Included Software:
    - Apple Health: software/applehealth.md
    - Bitwarden: software/bitwarden.md
    - Convos: software/convos.md
    - Darksky: software/darksky.md
    - Dasher: software/dasher.md
    - Emby: software/emby.md
    - Firefly III: software/firefly.md
    - Gitea: software/gitea.md
    - Grafana: software/grafana.md
    - Home Assistant: software/homeassistant.md
    - InfluxDB: software/influxdb.md
    - Jackett: software/jackett.md
    - Koel: software/koel.md
    - Matomo: software/matomo.md
    - Miniflux: software/miniflux.md
    - Minio: software/minio.md
    - Monica: software/monica.md
    - NextCloud: software/nextcloud.md
    - Paperless: software/paperless.md
    - Pi-hole: software/pihole.md
    - Portainer: software/portainer.md
    - Radarr / Sonarr: software/radarr-sonarr.md
    - Synchthing: software/syncthing.md
    - The Lounge: software/thelounge.md
    - Transmission: software/transmission.md
