---

- hosts: all
  become: "True"

  tasks:
    - name: Restart services
      systemd:
        name: "{{ service_item }}"
        state: restarted
        enabled: true
      when: "query"
      loop: "{{ services | flatten(1) }}"
      loop_control:
        loop_var: service_item
      ignore_errors: "yes"
      vars:
        query: "{{ service_item + '.enable' }}"

# Migration v0.7
    - name: remove docker-compose.SERVICENAME.yml
      file:
        state: absent
        path: "{{ volumes_root }}/{{ service_item }}/docker-compose.{{ service_item }}.yml"
      when: "query"
      loop: "{{ services|flatten(levels=1) }}"
      loop_control:
        loop_var: service_item
      ignore_errors: "yes"
      vars:
        query: "{{ service_item + '.enable' }}"
# End Migration v0.7
