---

- hosts: all
  become: "True"
  # gather_facts: "True"
  tags: common

  tasks:
    - name: Restart services
      systemd:
        name: "{{ service_item }}"
        state: restarted
      when: query
      loop: "{{ services|flatten(levels=1) }}"
      loop_control:
        loop_var: service_item
      vars:
        query: "{{ service_item + '.enable' }}"
