---
- name: Make mailserver directory.
  file:
    path: "/var/homelabos/mailserver"
    state: directory

# TODO: Remove postfix

- name: Copy mailserver docker-compose.yml file into place.
  template:
    src: docker-compose.mailserver.yml.j2
    dest: /var/homelabos/mailserver/docker-compose.mailserver.yml
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"

- name: Configure mailserver systemd service.
  template: src=service.j2 dest=/etc/systemd/system/mailserver.service

- name: Start mailserver
  systemd:
    name: mailserver
    enabled: "yes"
    daemon-reload: "yes"
    state: started
