---
- name: Make samba directory.
  file:
    path: "{{ volumes_root }}/samba"
    state: directory

- name: Copy samba docker-compose.yml file into place.
  template:
    src: docker-compose.samba.yml.j2
    dest: "{{ volumes_root }}/samba/docker-compose.yml"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"

- name: Configure samba systemd service.
  template:
    src: service.j2
    dest: /etc/systemd/system/samba.service

- name: Start samba
  systemd:
    name: samba
    enabled: "yes"
    daemon-reload: "yes"
    state: started
