---
- name: Make searx directory.
  file:
    path: "{{ volumes_root }}/searx"
    state: directory

- name: Copy Searx settins file.
  template:
    src: settings.yml.j2
    dest: "{{ volumes_root }}/searx/settings.yml"

- name: Copy searx docker-compose.yml file into place.
  template:
    src: docker-compose.searx.yml.j2
    dest: "{{ volumes_root }}/searx/docker-compose.searx.yml"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"

- name: Configure searx systemd service.
  template:
    src: service.j2
    dest: /etc/systemd/system/searx.service

- name: Start searx
  systemd:
    name: searx
    enabled: "yes"
    daemon-reload: "yes"
    state: started
