---
- name: Verify existence of DO token
  fail: 
    msg: "No valid DO access token found.  Please run 'make set do_access_token <token>' before attempting terraform."
  when: not do_access_token

- name: Generate Terraform file
  template:
    src: 'provider.tf.j2'
    dest: '{{ playbook_dir }}/settings/provider.tf'

- name: Generate Terraform file
  template:
    src: 'cloud_homelabos.tf.j2'
    dest: '{{ playbook_dir }}/settings/cloud_homelabos.tf'

- name: Generate Terraform file
  template:
    src: 'terraform.tfvars.j2'
    dest: '{{ playbook_dir }}/settings/terraform.tfvars'
...
