---
- name: Make n8n directory.
  file:
    path: "{{ volumes_root }}/n8n"
    state: directory

- name: Copy n8n docker-compose.yml file into place.
  template:
    src: docker-compose.n8n.yml.j2
    dest: "{{ volumes_root }}/n8n/docker-compose.yml"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"

- name: Configure n8n systemd service.
  template:
    src: service.j2
    dest: /etc/systemd/system/n8n.service

- name: Start n8n
  systemd:
    name: n8n
    enabled: "yes"
    daemon-reload: "yes"
    state: started
