---
- name: Make bookstack directory.
  file:
    path: "{{ volumes_root }}/bookstack"
    state: directory

- name: Make uploads directory.
  file:
    path: "{{ volumes_root }}/bookstack/uploads"
    state: directory
    # This sets the directory to www-data/www-data ownership inside the container
    owner: '33'
    group: '33'
    mode: '0755'

- name: Make storage uploads directory.
  file:
    path: "{{ volumes_root }}/bookstack/storage-uploads"
    state: directory
    # This sets the directory to www-data/www-data ownership inside the container
    owner: '33'
    group: '33'
    mode: '0755'

- name: Copy bookstack docker-compose.yml file into place.
  template:
    src: docker-compose.bookstack.yml.j2
    dest: "{{ volumes_root }}/bookstack/docker-compose.yml"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"

- name: Configure bookstack systemd service.
  template:
    src: service.j2
    dest: /etc/systemd/system/bookstack.service

- name: Start bookstack
  systemd:
    name: bookstack
    enabled: "yes"
    daemon-reload: "yes"
    state: started
