- debug:
    msg: "Port: {{item.key}} - {{item.value}}"
  loop: "{{ ports }}"
  when: "'bastion' in group_names"

- debug:
    msg: "group_names = {{group_names}}"

- name: Setup Port-forwarding per service.
  include_tasks:
    name: forward.yml
  when:
    - query
    - "lookup('vars', service_item).bastion_ports | dict2items is any"
  loop: "{{ services | flatten(1) }}"
  loop_control:
    loop_var: service_item
  vars:
    ports: "{{lookup('vars', service_item).bastion_ports | dict2items}}"
