- name: Establish DNAT rules
  iptables:
    table: nat
    chain: PREROUTING
    in_interface: "{{ bastion.interface }}"
    protocol: tcp
    destination_port: "{{ item.key }}"
    to_destination: "{{ bastion.wireguard.homelab_vpn_address }}:{{ item.value }}"
    jump: DNAT
  loop: "{{ bastion.ports_to_forward | dict2items }}"
  become: true

- name: Establish SNAT rules
  iptables:
    table: nat
    chain: POSTROUTING
    out_interface: wg0
    protocol: tcp
    to_source: "{{ bastion.wireguard.bastion_vpn_address }}"
    jump: SNAT
  loop: "{{ bastion.ports_to_forward | dict2items }}"
  become: true

- name: Set ipTables post-routing masquerade
  iptables:
    table: nat
    chain: POSTROUTING
    jump: MASQUERADE
  become: true
  when: "'bastion' in group_names"

- name: Persist iptable routing across reboots
  shell: iptables-save > /etc/iptables/rules.v4
  when: "'bastion' in group_names"

- name: Enable IP Forwarding
  shell: sysctl net.ipv4.ip_forward=1
  when: "'bastion' in group_names"
