- name: Setup Port-forwarding per service.
  include_tasks: forward.yml
  when:
    - query
    - "lookup('vars', service_item).bastion_ports | dict2items is any"
  loop: "{{ services | flatten(1) }}"
  loop_control:
    loop_var: service_item
  vars:
    ports: "{{lookup('vars', service_item).bastion_ports | dict2items}}"

- name: Set ipTables post-routing masquerade
  iptables:
    table: nat
    chain: POSTROUTING
    jump: MASQUERADE
  become: true
  when: "'bastion' in group_names"

- name: Persist iptable routing across reboots
  shell: iptables-save > /etc/iptables/rules.v4
  when: "'bastion' in group_names"

- name: Enable IP Forwarding
  shell: sysctl net.ipv4.ip_forward=1
  when: "'bastion' in group_names"
