---
- name: Make barcodebuddy directory.
  file:
    path: "{{ volumes_root }}/barcodebuddy"
    state: directory

- name: Copy barcodebuddy docker-compose.yml file into place.
  template:
    src: docker-compose.barcodebuddy.yml.j2
    dest: "{{ volumes_root }}/barcodebuddy/docker-compose.barcodebuddy.yml"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"

- name: Configure barcodebuddy systemd service.
  template:
    src: service.j2
    dest: /etc/systemd/system/barcodebuddy.service

- name: Start barcodebuddy
  systemd:
    name: barcodebuddy
    enabled: "yes"
    daemon-reload: "yes"
    state: started
