---
- name: Make gitea directory.
  file:
    path: "{{ volumes_root }}/gitea"
    state: directory

- name: Check that old db folder exists
  stat:
    path: "{{ volumes_root }}/gitea_db"
  register: old_gitea_db

- name: Move old db folder to new location
  command: mv "{{ volumes_root }}/gitea_db" "{{ volumes_root }}/gitea/db"
  when: old_gitea_db.stat.exists and old_gitea_db.stat.isdir

- name: Copy gitea docker-compose.yml file into place.
  template:
    src: docker-compose.gitea.yml.j2
    dest: "{{ volumes_root }}/gitea/docker-compose.yml"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"

- name: Configure gitea systemd service.
  template:
    src: service.j2
    dest: /etc/systemd/system/gitea.service

- name: Start gitea
  systemd:
    name: gitea
    enabled: "yes"
    daemon-reload: "yes"
    state: started
