---
- name: Make simplyshorten directory.
  file:
    path: "{{ volumes_root }}/simplyshorten"
    state: directory

- name: Copy simplyshorten docker-compose.yml file into place.
  template:
    src: docker-compose.simplyshorten.yml.j2
    dest: "{{ volumes_root }}/simplyshorten/docker-compose.yml"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"

- name: Configure simplyshorten systemd service.
  template:
    src: service.j2
    dest: /etc/systemd/system/simplyshorten.service

- name: Start simplyshorten
  systemd:
    name: simplyshorten
    enabled: "yes"
    daemon-reload: "yes"
    state: started
