---
- name: Make authelia directory.
  file:
    path: "/var/homelabos/authelia"
    state: directory

- name: Copy authelia docker-compose.yml file into place.
  template:
    src: docker-compose.authelia.yml.j2
    dest: /var/homelabos/authelia/docker-compose.authelia.yml

- name: Copy authelia_config.yml file into place.
  template:
    src: authelia_config.yml.j2
    dest: /var/homelabos/authelia/authelia_config.yml

- name: Configure authelia systemd service.
  template:
    src: service.j2
    dest: /etc/systemd/system/authelia.service

- name: Configure base ldif file.
  template:
    src: base.ldif.j2
    dest: /var/homelabos/authelia/ldap/base.ldif

- name: Configure access rules.
  template:
    src: access.rules.j2
    dest: /var/homelabos/authelia/ldap/access.rules

- name: Start authelia
  systemd:
    name: authelia
    enabled: "yes"
    daemon-reload: "yes"
    state: started
