---
- name: Make sonarr directory.
  file:
    path: "{{ volumes_root }}/sonarr"
    state: directory

- name: Copy sonarr docker-compose.yml file into place.
  template:
    src: docker-compose.sonarr.yml.j2
    dest: "{{ volumes_root }}/sonarr/docker-compose.sonarr.yml"


- name: Configure sonarr systemd service.
  template:
    src: service.j2
    dest: /etc/systemd/system/sonarr.service

- name: Start sonarr
  systemd:
    name: sonarr
    enabled: "yes"
    daemon-reload: "yes"
    state: started
