---
- name: Make emby directory.
  file:
    path: "{{ volumes_root }}/emby"
    state: directory

- name: Copy emby docker-compose.yml file into place.
  template:
    src: docker-compose.emby.yml.j2
    dest: "{{ volumes_root }}/emby/docker-compose.yml"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"

- name: Configure emby systemd service.
  template:
    src: service.j2
    dest: /etc/systemd/system/emby.service

- name: Start emby
  systemd:
    name: emby
    enabled: "yes"
    daemon-reload: "yes"
    state: started
