---
- name: Make nodered directory.
  file:
    path: "{{ volumes_root }}/nodered"
    state: directory

# Node-RED container runs with UID 1000
- name: Create data directory and set permissions
  file:
    path: "{{ volumes_root }}/nodered/data"
    state: directory
    mode: '0755'
    owner: '1000'
    group: '1000'

- name: Copy nodered docker-compose.yml file into place.
  template:
    src: docker-compose.nodered.yml.j2
    dest: "{{ volumes_root }}/nodered/docker-compose.yml"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"

- name: Configure nodered systemd service.
  template:
    src: service.j2
    dest: /etc/systemd/system/nodered.service

- name: Start nodered
  systemd:
    name: nodered
    enabled: "yes"
    daemon-reload: "yes"
    state: started
