---
- name: Make rsshub directory.
  file:
    path: "{{ volumes_root }}/rsshub"
    state: directory

- name: Copy rsshub docker-compose.yml file into place.
  template:
    src: docker-compose.rsshub.yml.j2
    dest: "{{ volumes_root }}/rsshub/docker-compose.yml"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"

- name: Configure rsshub systemd service.
  template:
    src: service.j2
    dest: /etc/systemd/system/rsshub.service

- name: Start rsshub
  systemd:
    name: rsshub
    enabled: "yes"
    daemon-reload: "yes"
    state: started
