---
- name: Read Tor SSH connection info
  shell: cat /var/lib/tor/ssh-onion/hostname
  register: tor_ssh_domain_file
  when: enable_tor

- name: Read Tor connection info
  shell: cat /var/lib/tor/http-onion/hostname
  register: tor_http_domain_file
  when: enable_tor

- name: remove enabled services.
  file:
    state: absent
    path: "/var/homelabos/{{service_item}}"
  when: "enabled_services[service_item]"
  loop: "{{ services|flatten(levels=1) }}"
  loop_control:
    loop_var: service_item
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"

- debug:
    msg: "Package removed successfully! Go to https://{{ domain }}/ to get started."

- debug:
    msg: "Problems? File an issue at https://gitlab.com/NickBusey/HomelabOS/issues"
