---
- name: Make mstream directory.
  file:
    path: "/var/homelabos/mstream"
    state: directory

- name: Copy mstream docker-compose.yml file into place.
  template:
    src: docker-compose.mstream.yml.j2
    dest: /var/homelabos/mstream/docker-compose.mstream.yml

- name: Configure mstream systemd service.
  template:
    src: service.j2
    dest: /etc/systemd/system/mstream.service

- name: Start mstream
  systemd:
    name: mstream
    enabled: "yes"
    daemon-reload: "yes"
    state: started
