---
- name: Make HomelabOS documentation directory.
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /var/homelabos
    - /var/homelabos/docs

- name: Configure HomelabOS Documentation.
  copy: src=site dest=/var/homelabos/docs