---
- name: Make grocy directory.
  file:
    path: "/var/homelabos/grocy"
    state: directory

- name: Copy grocy docker-compose.yml file into place.
  template:
    src: docker-compose.grocy.yml.j2
    dest: /var/homelabos/grocy/docker-compose.grocy.yml

- name: Configure grocy systemd service.
  template:
    src: service.j2
    dest: /etc/systemd/system/grocy.service

- name: Start grocy
  systemd:
    name: grocy
    enabled: "yes"
    daemon-reload: "yes"
    state: started
