---
- name: Make homedash directory.
  file:
    path: "/var/homelabos/homedash"
    state: directory

- name: Copy homedash docker-compose.yml file into place.
  template:
    src: docker-compose.homedash.yml.j2
    dest: /var/homelabos/homedash/docker-compose.homedash.yml
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"

- name: Configure homedash systemd service.
  template: src=service.j2 dest=/etc/systemd/system/homedash.service

- name: Start homedash
  systemd:
    name: homedash
    enabled: "yes"
    daemon-reload: "yes"
    state: started
