---
- name: Make turtl directory.
  file:
    path: "{{ volumes_root }}/turtl"
    state: directory

- name: Check out Turtl server git repo
  git:
    repo: https://github.com/turtl/server.git
    dest: "{{ volumes_root }}/turtl/server"

- name: Copy turtl docker-compose.yml file into place.
  template:
    src: docker-compose.turtl.yml.j2
    dest: "{{ volumes_root }}/turtl/docker-compose.yml"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"

- name: Start database to create user and empty database. Turtl is not resilient for waiting by itself.
  docker_compose:
    project_src: "{{ volumes_root }}/turtl"
    services:
      - postgres-db
    state: present

- name: Build Turtl project from docker-compose
  docker_compose:
    project_src: "{{ volumes_root }}/turtl"
    build: yes

#- pause:
#    seconds: 20

#- name: Delete the Turtl Git checkout from the volume_root
#  file:
#    path: "{{ volumes_root }}/turtl/server"
#    state: absent

- name: Configure turtl systemd service.
  template:
    src: service.j2
    dest: /etc/systemd/system/turtl.service

- name: Start turtl
  systemd:
    name: turtl
    enabled: "yes"
    daemon-reload: "yes"
    state: started
