---
- name: Create Media Folders / NAS Mount Points
  file:
    path: "{{ storage_dir }}/{{ item }}"
    state: directory
  with_items:
    - "Backups"
    - "Books"
    - "Documents"
    - "Downloads"
    - "Music"
    - "Pictures"
    - "temp"
    - "Video"
  become: yes

- name: Configure NAS - Public NFS Shares
  when:
    - nas_mount_type == "nfs"
  lineinfile:
    path: /etc/fstab
    line: "{{ nas_host }}:{{ nas_share_path }}/{{ item }} \
      {{ storage_dir }}/{{ item }} nfs \
      auto,nofail,noatime,nolock,intr,tcp,actimeo=1800 0 0"
  with_items:
    - "Backups"
    - "Books"
    - "Documents"
    - "Downloads"
    - "Music"
    - "Pictures"
    - "temp"
    - "Video"
  become: yes

- name: Configure NAS - Samba Shares
  when:
    - nas_mount_type == "smb" or nas_mount_type == "cifs"
  lineinfile:
    path: /etc/fstab
    line: "//{{ nas_host }}/{{ nas_share_path }}/{{ item }} \
      {{ storage_dir }}/{{ item }} cifs \
      nobrl,username={{ nas_user }},vers=2.0,\
      dom={{ nas_workgroup }},password={{ nas_pass }},\
      uid={{ uid_output.stdout }},gid={{ gid_output.stdout }},\
      iocharset=utf8,file_mode=0777,dir_mode=0770  0  0"
  with_items:
    - "Backups"
    - "Books"
    - "Documents"
    - "Downloads"
    - "Music"
    - "Pictures"
    - "temp"
    - "Video"
  become: yes

- name: Mount NAS Drives
  command: mount -a
  args:
    warn: "no"
  ignore_errors: "yes"
  become: yes
