---
- name: Make quakejs directory.
  file:
    path: "{{ volumes_root }}/quakejs"
    state: directory

- name: Copy quakejs docker-compose.yml file into place.
  template:
    src: docker-compose.quakejs.yml.j2
    dest: "{{ volumes_root }}/quakejs/docker-compose.yml"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"

- name: Configure quakejs systemd service.
  template:
    src: service.j2
    dest: /etc/systemd/system/quakejs.service

- name: Start quakejs
  systemd:
    name: quakejs
    enabled: "yes"
    daemon-reload: "yes"
    state: started
